<a href="https://colab.research.google.com/github/Raghav847/pytorch_learn/blob/main/notebooks/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


In [4]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
scalar.item()

7

In [7]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

Random Tensors

In [16]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.1638, 0.0299, 0.7422, 0.8781],
        [0.2127, 0.0254, 0.0912, 0.9895],
        [0.1769, 0.9218, 0.3605, 0.2315]])

In [17]:
random_tensor.ndim

2

In [18]:
random_tensor.shape

torch.Size([3, 4])

In [19]:
random_image_size_tensor = torch.rand(size=(224, 224, 3)) #h, w, color channels(R B G)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

Zeros and Ones

In [20]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
ones.dtype

torch.float32

In [23]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

In [25]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [26]:
float_32_tensor.dtype

torch.float32

In [27]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [28]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [29]:
int_32_tensor * float_32_tensor

tensor([ 9., 36., 81.])

## Tensor Info

In [30]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.5548, 0.4729, 0.5791, 0.5539],
        [0.5627, 0.3322, 0.3801, 0.3806],
        [0.0549, 0.0493, 0.8255, 0.3348]])

In [31]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.5548, 0.4729, 0.5791, 0.5539],
        [0.5627, 0.3322, 0.3801, 0.3806],
        [0.0549, 0.0493, 0.8255, 0.3348]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


## Tensor Operations

In [32]:
tensor = torch.tensor([1, 2, 3])
tensor + 100

tensor([101, 102, 103])

In [33]:
tensor = tensor * 10

In [34]:
tensor

tensor([10, 20, 30])

In [35]:
tensor - 10

tensor([ 0, 10, 20])

In [36]:
torch.mul(tensor, 10)

tensor([100, 200, 300])

## Matrix Multiplication

In [37]:
print(tensor, '*', tensor)
print(f"Equals: {tensor * tensor}")

tensor([10, 20, 30]) * tensor([10, 20, 30])
Equals: tensor([100, 400, 900])


In [38]:
torch.matmul(tensor, tensor)

tensor(1400)

In [39]:
%%time
val = 0
for i in range(len(tensor)):
  val += tensor[i] * tensor[i]
print(val)

tensor(1400)
CPU times: user 1.29 ms, sys: 32 µs, total: 1.32 ms
Wall time: 1.06 ms


In [40]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 178 µs, sys: 20 µs, total: 198 µs
Wall time: 178 µs


tensor(1400)

In [41]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 4))

tensor([[0.5644, 0.8992, 0.8584, 1.3607],
        [0.5991, 0.9586, 0.8350, 1.4374],
        [0.1000, 0.1547, 0.2374, 0.2489]])

In [42]:
tensor_A = torch.rand(size=(3,2))
tensor_B = torch.rand(size=(3,2))
tensor_A


tensor([[0.7543, 0.1171],
        [0.4816, 0.6314],
        [0.3634, 0.1437]])

In [43]:
tensor_B

tensor([[0.2475, 0.4591],
        [0.1562, 0.6388],
        [0.1974, 0.0501]])

In [44]:
tensor_B.shape

torch.Size([3, 2])

In [45]:
tensor_B.T.shape

torch.Size([2, 3])

In [46]:
tensor_C = tensor_A @ tensor_B.T

In [47]:
tensor_C.shape

torch.Size([3, 3])

##Tensor Aggregation

In [48]:
x = torch.arange(1, 100, 10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [49]:
torch.min(x), x.min()

(tensor(1), tensor(1))

In [50]:
torch.max(x) , x.max()

(tensor(91), tensor(91))

In [51]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [52]:
torch.sum(x), x.sum()

(tensor(460), tensor(460))

##positional min and max

In [53]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [54]:
x.argmin()

tensor(0)

In [55]:
x[0]

tensor(1)

In [56]:
x.argmax()

tensor(9)

In [57]:
x[9]

tensor(91)

## Reshaping, stacking, squeezing and unsqueezing

In [58]:
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [59]:
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [60]:
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [61]:
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [62]:
x_reshaped.shape

torch.Size([1, 9])

In [63]:
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [64]:
x_squeezed = x_reshaped.squeeze()

In [65]:
x_reshaped.squeeze().shape

torch.Size([9])

In [66]:
print(f"Previous: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

x_unsqueezed = x_squeezed.unsqueeze(dim=0)

print(f"\nNew: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [67]:
x_original = torch.rand(size=(224, 224, 3))

x_permuted = x_original.permute(2, 0, 1)
print(f"Previous shape: {x_original.shape}")
print(f"new shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
new shape: torch.Size([3, 224, 224])


##Indexing

In [68]:
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [69]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [70]:
x[0][0]

tensor([1, 2, 3])

In [71]:
x[0][0][0]

tensor(1)

In [72]:
x[0][1]

tensor([4, 5, 6])

In [73]:
x[0][2][2]

tensor(9)

In [74]:
x[:, 0]

tensor([[1, 2, 3]])

In [75]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [76]:
x[:, 1, 1]

tensor([5])

In [77]:
x[0, 0, :]

tensor([1, 2, 3])

##Pytorch and Numpy

In [78]:
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [79]:
array = array + 1
array

array([2., 3., 4., 5., 6., 7., 8.])

In [80]:
tensor

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

In [81]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [82]:
tensor += 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([2., 2., 2., 2., 2., 2., 2.], dtype=float32))

##Reproduce

In [83]:
import torch

random_A = torch.rand(3, 4)
random_B = torch.rand(3, 4)

print(random_A == random_B)

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [84]:
RANDOM_SEED = 847
torch.manual_seed(RANDOM_SEED)
random_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_D = torch.rand(3, 4)
print(random_C == random_D)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


##GPU access

In [85]:
!nvidia-smi

Wed Oct  8 03:05:06 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A100-SXM4-40GB          Off |   00000000:00:04.0 Off |                    0 |
| N/A   31C    P0             44W /  400W |       0MiB /  40960MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+-----

In [87]:
import torch
torch.cuda.is_available()

True

## Device agnostic code

In [88]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [89]:
torch.cuda.device_count()

1

## Tensor and GPU

In [90]:
tensor = torch.tensor([1, 2, 3])

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [91]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

## GPU -> CPU

In [92]:
tensor_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_on_cpu

array([1, 2, 3])

In [93]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')