<a href="https://colab.research.google.com/github/Raghav847/pytorch_learn/blob/main/notebooks/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [12]:
TENSOR.ndim

3

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

Random Tensors

In [14]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.1534, 0.6901, 0.1887, 0.9859],
        [0.7872, 0.5857, 0.4838, 0.5093],
        [0.6975, 0.7709, 0.2758, 0.3300]])

In [15]:
random_tensor.ndim

2

In [16]:
random_tensor.shape

torch.Size([3, 4])

In [17]:
random_image_size_tensor = torch.rand(size=(224, 224, 3)) #h, w, color channels(R B G)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

Zeros and Ones

In [18]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [20]:
ones.dtype

torch.float32

In [26]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

In [30]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [31]:
float_32_tensor.dtype

torch.float32

In [32]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [33]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [34]:
int_32_tensor * float_32_tensor

tensor([ 9., 36., 81.])

## Tensor Info

In [35]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.7442, 0.6633, 0.3612, 0.7795],
        [0.0923, 0.6886, 0.8246, 0.6229],
        [0.6493, 0.8599, 0.5583, 0.7309]])

In [37]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.7442, 0.6633, 0.3612, 0.7795],
        [0.0923, 0.6886, 0.8246, 0.6229],
        [0.6493, 0.8599, 0.5583, 0.7309]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


## Tensor Operations

In [40]:
tensor = torch.tensor([1, 2, 3])
tensor + 100

tensor([101, 102, 103])

In [42]:
tensor = tensor * 10

In [43]:
tensor

tensor([10, 20, 30])

In [44]:
tensor - 10

tensor([ 0, 10, 20])

In [45]:
torch.mul(tensor, 10)

tensor([100, 200, 300])

## Matrix Multiplication

In [47]:
print(tensor, '*', tensor)
print(f"Equals: {tensor * tensor}")

tensor([10, 20, 30]) * tensor([10, 20, 30])
Equals: tensor([100, 400, 900])


In [48]:
torch.matmul(tensor, tensor)

tensor(1400)

In [50]:
%%time
val = 0
for i in range(len(tensor)):
  val += tensor[i] * tensor[i]
print(val)

tensor(1400)
CPU times: user 2.09 ms, sys: 1.97 ms, total: 4.06 ms
Wall time: 3.99 ms


In [51]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 280 µs, sys: 0 ns, total: 280 µs
Wall time: 170 µs


tensor(1400)

In [52]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 4))

tensor([[0.7795, 0.9119, 0.8861, 0.3445],
        [0.7419, 0.8632, 0.8429, 0.3217],
        [0.6317, 0.7206, 0.7167, 0.2547]])

In [54]:
tensor_A = torch.rand(size=(3,2))
tensor_B = torch.rand(size=(3,2))
tensor_A


tensor([[0.9778, 0.4695],
        [0.4072, 0.9548],
        [0.5141, 0.3861]])

In [55]:
tensor_B

tensor([[0.3177, 0.3487],
        [0.3437, 0.4570],
        [0.7432, 0.5930]])

In [56]:
tensor_B.shape

torch.Size([3, 2])

In [57]:
tensor_B.T.shape

torch.Size([2, 3])

In [59]:
tensor_C = tensor_A @ tensor_B.T

In [60]:
tensor_C.shape

torch.Size([3, 3])