<a href="https://colab.research.google.com/github/Raghav847/pytorch_learn/blob/main/notebooks/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [12]:
TENSOR.ndim

3

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

Random Tensors

In [14]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.0949, 0.0988, 0.3934, 0.7895],
        [0.1687, 0.9352, 0.1699, 0.1666],
        [0.8355, 0.7640, 0.8412, 0.0845]])

In [15]:
random_tensor.ndim

2

In [16]:
random_tensor.shape

torch.Size([3, 4])

In [17]:
random_image_size_tensor = torch.rand(size=(224, 224, 3)) #h, w, color channels(R B G)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

Zeros and Ones

In [18]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [20]:
ones.dtype

torch.float32

In [21]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

In [23]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [24]:
float_32_tensor.dtype

torch.float32

In [25]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [26]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [27]:
int_32_tensor * float_32_tensor

tensor([ 9., 36., 81.])

## Tensor Info

In [28]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.1892, 0.5877, 0.9279, 0.0538],
        [0.2272, 0.2589, 0.2686, 0.4233],
        [0.5568, 0.6269, 0.1699, 0.4633]])

In [29]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.1892, 0.5877, 0.9279, 0.0538],
        [0.2272, 0.2589, 0.2686, 0.4233],
        [0.5568, 0.6269, 0.1699, 0.4633]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


## Tensor Operations

In [30]:
tensor = torch.tensor([1, 2, 3])
tensor + 100

tensor([101, 102, 103])

In [31]:
tensor = tensor * 10

In [32]:
tensor

tensor([10, 20, 30])

In [33]:
tensor - 10

tensor([ 0, 10, 20])

In [34]:
torch.mul(tensor, 10)

tensor([100, 200, 300])

## Matrix Multiplication

In [35]:
print(tensor, '*', tensor)
print(f"Equals: {tensor * tensor}")

tensor([10, 20, 30]) * tensor([10, 20, 30])
Equals: tensor([100, 400, 900])


In [36]:
torch.matmul(tensor, tensor)

tensor(1400)

In [37]:
%%time
val = 0
for i in range(len(tensor)):
  val += tensor[i] * tensor[i]
print(val)

tensor(1400)
CPU times: user 1.45 ms, sys: 748 µs, total: 2.19 ms
Wall time: 3.71 ms


In [38]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 919 µs, sys: 153 µs, total: 1.07 ms
Wall time: 2.07 ms


tensor(1400)

In [39]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 4))

tensor([[0.5247, 0.4411, 0.6167, 0.7019],
        [0.6896, 0.7079, 0.8304, 1.2473],
        [0.6706, 0.5670, 0.7887, 0.9053]])

In [40]:
tensor_A = torch.rand(size=(3,2))
tensor_B = torch.rand(size=(3,2))
tensor_A


tensor([[0.7665, 0.1547],
        [0.1261, 0.6139],
        [0.1307, 0.2981]])

In [41]:
tensor_B

tensor([[0.8337, 0.9372],
        [0.9975, 0.2672],
        [0.3522, 0.3922]])

In [42]:
tensor_B.shape

torch.Size([3, 2])

In [43]:
tensor_B.T.shape

torch.Size([2, 3])

In [44]:
tensor_C = tensor_A @ tensor_B.T

In [45]:
tensor_C.shape

torch.Size([3, 3])

##Tensor Aggregation

In [54]:
x = torch.arange(1, 100, 10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [55]:
torch.min(x), x.min()

(tensor(1), tensor(1))

In [56]:
torch.max(x) , x.max()

(tensor(91), tensor(91))

In [57]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [58]:
torch.sum(x), x.sum()

(tensor(460), tensor(460))

##positional min and max

In [59]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [60]:
x.argmin()

tensor(0)

In [61]:
x[0]

tensor(1)

In [62]:
x.argmax()

tensor(9)

In [63]:
x[9]

tensor(91)

## Reshaping, stacking, squeezing and unsqueezing

In [67]:
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [68]:
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [69]:
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [72]:
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [73]:
x_reshaped.shape

torch.Size([1, 9])

In [74]:
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [79]:
x_squeezed = x_reshaped.squeeze()

In [80]:
x_reshaped.squeeze().shape

torch.Size([9])

In [82]:
print(f"Previous: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

x_unsqueezed = x_squeezed.unsqueeze(dim=0)

print(f"\nNew: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [84]:
x_original = torch.rand(size=(224, 224, 3))

x_permuted = x_original.permute(2, 0, 1)
print(f"Previous shape: {x_original.shape}")
print(f"new shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
new shape: torch.Size([3, 224, 224])


##Indexing

In [86]:
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [87]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [88]:
x[0][0]

tensor([1, 2, 3])

In [89]:
x[0][0][0]

tensor(1)

In [91]:
x[0][1]

tensor([4, 5, 6])

In [92]:
x[0][2][2]

tensor(9)

In [93]:
x[:, 0]

tensor([[1, 2, 3]])

In [94]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [95]:
x[:, 1, 1]

tensor([5])

In [96]:
x[0, 0, :]

tensor([1, 2, 3])

##Pytorch and Numpy

In [97]:
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [100]:
array = array + 1
array

array([3., 4., 5., 6., 7., 8., 9.])

In [101]:
tensor

tensor([2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64)

In [104]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [105]:
tensor += 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([2., 2., 2., 2., 2., 2., 2.], dtype=float32))

##Reproduce

In [106]:
import torch

random_A = torch.rand(3, 4)
random_B = torch.rand(3, 4)

print(random_A == random_B)

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [108]:
RANDOM_SEED = 847
torch.manual_seed(RANDOM_SEED)
random_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_D = torch.rand(3, 4)
print(random_C == random_D)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
