<a href="https://colab.research.google.com/github/Raghav847/pytorch_learn/blob/main/notebooks/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [12]:
TENSOR.ndim

3

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

Random Tensors

In [14]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4251, 0.6350, 0.3874, 0.0180],
        [0.1854, 0.8621, 0.0022, 0.0826],
        [0.9253, 0.7862, 0.0722, 0.6267]])

In [15]:
random_tensor.ndim

2

In [17]:
random_tensor.shape

torch.Size([3, 4])

In [19]:
random_image_size_tensor = torch.rand(size=(224, 224, 3)) #h, w, color channels(R B G)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)